# Generated by Django 4.2.1 on 2023-05-30 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['licence_plate'], 'verbose_name': 'car', 'verbose_name_plural': 'cars'},
        ),
        migrations.AlterModelOptions(
            name='carmodel',
            options={'ordering': ['make', 'model', 'year', 'engine'], 'verbose_name': 'car model', 'verbose_name_plural': 'car models'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['date', 'id'], 'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
        migrations.AlterModelOptions(
            name='orderlist',
            options={'verbose_name': 'order List', 'verbose_name_plural': 'order Lists'},
        ),
        migrations.RemoveField(
            model_name='car',
            name='car_model',
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='service.carmodel', verbose_name='model'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, default=1, max_digits=10, verbose_name='price'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='customer',
            field=models.CharField(db_index=True, max_length=50, verbose_name='client'),
        ),
        migrations.AlterField(
            model_name='car',
            name='licence_plate',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Licence Plate'),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin_code',
            field=models.CharField(db_index=True, max_length=50, verbose_name='VIN Code'),
        ),
        migrations.AlterField(
            model_name='order',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='service.car', verbose_name='car'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.CharField(db_index=True, max_length=50, verbose_name='data'),
        ),
    ]
