# Generated by Django 4.2.1 on 2023-05-30 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_carmodel_options_alter_order_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=50, verbose_name='quantity')),
                ('price', models.CharField(max_length=50, verbose_name='price')),
            ],
            options={
                'verbose_name': 'order entry',
                'verbose_name_plural': 'order entries',
            },
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name', 'price'], 'verbose_name': 'service', 'verbose_name_plural': 'services'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.DeleteModel(
            name='OrderList',
        ),
        migrations.AddField(
            model_name='orderentry',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_enteries', to='service.order', verbose_name='order'),
        ),
        migrations.AddField(
            model_name='orderentry',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', related_query_name='order_enteries', to='service.service'),
        ),
    ]
