# Generated by Django 4.2.1 on 2023-05-31 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_orderentry_alter_service_options_remove_order_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Available'), (1, 'Reserved'), (2, 'Taken'), (3, 'Unavailable'), (7, 'Broken')], db_index=True, default=0, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='engine',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Engine'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='make',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Make'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='model',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Year'),
        ),
    ]
