# Generated by Django 4.2.1 on 2023-05-31 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_remove_order_status_orderentry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderentry',
            name='status',
            field=models.CharField(choices=[(0, 'Waiting'), (1, 'New'), (2, 'Processing'), (3, 'Complete'), (7, 'Cancelled')], db_index=True, default='new', max_length=20, verbose_name='Status'),
        ),
    ]
