# Generated by Django 4.2.1 on 2023-06-01 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_alter_orderentry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=18, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='service.car', verbose_name='car'),
        ),
        migrations.AlterField(
            model_name='orderentry',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_entries', to='service.order', verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='orderentry',
            name='price',
            field=models.CharField(default=0, max_length=50, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='orderentry',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', related_query_name='order_entries', to='service.service'),
        ),
        migrations.AlterField(
            model_name='orderentry',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('complete', 'Complete'), ('cancelled', 'Cancelled')], db_index=True, default=0, max_length=20, verbose_name='Status'),
        ),
    ]
