# Generated by Django 4.2.1 on 2023-06-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_order_price_alter_order_car_alter_orderentry_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderentry',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='price'),
        ),
    ]
