# Generated by Django 4.2.1 on 2023-06-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_remove_car_cover_carmodel_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderentry',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='total'),
        ),
        migrations.AlterField(
            model_name='orderentry',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='price'),
        ),
    ]
