# Generated by Django 4.2.1 on 2023-06-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_orderentry_total_alter_orderentry_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderentry',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=18, verbose_name='quantity'),
        ),
    ]
