# Generated by Django 4.2.1 on 2023-06-05 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0015_alter_car_customer_alter_order_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderentry',
            options={'verbose_name': 'order_entry', 'verbose_name_plural': 'order entries'},
        ),
        migrations.RemoveField(
            model_name='car',
            name='customer',
        ),
        migrations.AddField(
            model_name='car',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_entry', to=settings.AUTH_USER_MODEL, verbose_name='client'),
        ),
        migrations.AddField(
            model_name='car',
            name='note',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Client note'),
        ),
        migrations.AddField(
            model_name='order',
            name='due_back',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='due back'),
        ),
    ]
