# Generated by Django 4.2.1 on 2023-06-06 08:37

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_alter_orderentry_options_alter_car_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='note',
            field=tinymce.models.HTMLField(blank=True, max_length=50, null=True, verbose_name='Client note'),
        ),
    ]
