# Generated by Django 4.2.1 on 2023-06-07 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0018_alter_car_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(verbose_name='Created')),
                ('content', models.TextField(max_length=4000, verbose_name='content')),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_commenter', to=settings.AUTH_USER_MODEL, verbose_name='commenter')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='service.order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'order review',
                'verbose_name_plural': 'order reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
