# Generated by Django 4.2.1 on 2023-06-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0019_orderreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='service/car_foto', verbose_name='foto'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now=True, db_index=True, null=True, verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='orderreview',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Created'),
        ),
    ]
